# -*- coding: utf-8 -*-
"""Telecom_churn_EDA_done (altered).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ot67Vg4gu24b-U6uAbkypp8hEyJ_f6lM

#Telecom Customer Churn Prediction Model

**Project Background** : The Telecommunications companies faces challenges with customer churn rates higher the 10% annually.**To address this issue, the project aims to develop a classification model to predict customer churn based on individual features.**The goal is to leverage this data to create a predictive model that can help the company identify customers at risk of churning and implement retention strategies effectively.

The data set includes the following variables:
* state: Categorical, for the 51 states and the District of Columbia.
* Area.code
* account.length: how long the account has been active.
* voice.plan: yes or no, voicemail plan.
* voice.messages: number of voicemail messages.
* intl.plan: yes or no, international plan.
* intl.mins: minutes customer used service to make international calls.
* intl.calls: total number of international calls.
* intl.charge: total international charge.
* day.mins: minutes customer used service during the day.
* day.calls: total number of calls during the day.
* day.charge: total charge during the day.
* eve.mins: minutes customer used service during the evening.
* eve.calls: total number of calls during the evening.
* eve.charge: total charge during the evening.
* night.mins: minutes customer used service during the night.
* night.calls: total number of calls during the night.
* night.charge: total charge during the night.
* customer.calls: number of calls to customer service.
* churn(**Target**): Categorical, yes or no. Indicator of whether the customer has left the company (yes or no).

####Import the libraries
"""

!pip install category_encoders --quiet

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
#to ignore warnings
import warnings
warnings.filterwarnings('ignore')
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import category_encoders as ce
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

pd.set_option('display.max_columns',None)

"""# 1.Load the dataset

####Load the Raw-data    -> Data integration
"""

df = pd.read_csv("Churn (1).csv")

df.info()

"""* The  [day.charge ,eve.mins] columns are numerical values but are in object dtypes.So, we are changing them to { float } dtype  values(NUMERICAL VARIABLES).

#### All Data Types are mentioned correctly.
"""

column_dict = {"day.charge":float ,"eve.mins" :float}
df=df.astype(column_dict)                         # pd.astype("dict")          ->  returns the new df with changed dtypes

df.select_dtypes(include='object')                        # Categorical variables

"""* churn (yes || no) is the target output."""

df.select_dtypes(include=['int64','float64'])             #Numerical variables

"""# 2.Data Exploration

####Descriptive Statistics
"""

df.describe().T

df.describe(include ="all").T

"""* State has 51 unique values while area_code has 3 unique values . What is the relation ?
* Units for account length ?
"""

df.info()

"""* All the columns data types are correctly identified

#### In Data Analysis we will analyze to find out the below stuff
+ Missing values
+ All the Numerical Variables
+ Distribution of the Numerical Variables
+ Categorical Variables
+ Cardinality of Categorical Variables
+ Outliers
+ Relationshop between independent and dependent feature (Target)
"""

# print shape of dataset with rows and columns
print(df.shape)
# print top 5 records
df.head()

"""####2.1 Missing values

* ***There are no missing values in categorical values***
"""

df[(df['voice.plan'] == '') | (df['intl.plan'] == '') | (df['churn'] == '') | (df['state'] == '')|(df['area.code'] == '')]

df.isnull().sum()

"""[ Day.charge , eve.calls ] has missing values."""

(df.isnull().sum()/len(df))*100 >0

"""#### The percentage of missing values in the data is less than 0.5 % of the entire data ."""

df.sort_values(by ='day.charge',na_position='first').head(10)                   #sort_values

"""* There are 3 different types of Missing data that can be encountered.
1. MCAR ( Missing Completley At Random ) : The missing data is completly at random and is distributed randomly accross the data range ,not limiting to one specific range and is feature which has missing values not related/can be dependent to another feature .
2. MAR (Missing At Random ) : The missing data is observed randomly on the data and feature which has the dependency to another feature in the data.
3. MNAR (Missing Not At Random ) : The missing data is here , caused by a relationship between missing values of the data and observed values in the data itself.

* The feature day.charge has NULL values and the values are dependent on features day.mins and day.charge .So, it is MAR (Missing at Random )
"""

df.sort_values(by ='eve.mins',na_position='first')                              #sort_values

"""
* The feature eve.mins has NULL values and the values are dependent on features eve.calls and eve.charge .So, it is MAR (Missing at Random )  """

df=df.dropna()

df.isnull().sum()

"""* The null values have been dropped .

#### 2.2 Duplicated values
"""

df[df.duplicated()]

"""* There are no duplicates in the data frame."""

df.columns

"""* Feature Engineering prospects :
** day.charge, day.min ,day.calls --->"day charge per min" and "day charge per call"
* Simlarly , for the Eveing , Night ,International categories
"""

num_cols = df.select_dtypes(include = np.number).columns
num_cols                                                # Numerical feature columns

cat_cols = df.select_dtypes(include ='object').columns
cat_cols                                                 # Categorical feature columns

"""#### 2.3 Univarite analysis : Analyzing the variables using one feature at a time."""

def outliers (df,ft):
    outlier_dict = {}
    Q1=df[ft].quantile(0.25)
    Q3=df[ft].quantile(0.75)
    IQR= Q3-Q1

    LOWER_BOUND=Q1-1.5*IQR
    UPPER_BOUND=Q3+1.5*IQR

    ls=df.index[ (df[ft]< LOWER_BOUND) | (df[ft]> UPPER_BOUND) ]
    outlier_dict[ft]=ls
    return outlier_dict

index_list=[]
for feature in num_cols:
    index_list.append(outliers(df,feature))

index_list

def info(your_dict:dict)->None:
  for feature_name, indices_list in your_dict.items():
    global total_outliers
    total_outliers+=len(indices_list)
    print(f"The fetaure  '{feature_name}' has {len(indices_list)} outliers")

total_outliers = 0
for outlier_dict in index_list:
  info(outlier_dict)

print(f"The total number of outliers are {total_outliers}")

Outliers_percent= (100*total_outliers )/len(df)
Outliers_percent

"""We cannot remove 21 % of data as outliers as we might loose important inforamtion on large scale .

There are too many outliers compared to size of avialble data.SO,At this point we are not removing it.
"""

for col in num_cols:
  print("--------------\n")
  print("--------------\n")
  print(col)
  print('skew : ',round(df[col].skew(),2))
  plt.figure(figsize=(15,5))
  plt.subplot(1,2,1)
  sns.distplot(x=df[col],hist= True)                           # Frequency Distribution
  plt.ylabel("Count")
  plt.subplot(1,2,2)
  sns.boxplot(x=df[col])                              # Five Point Summary
  plt.show()

for col in num_cols:
    print("--------------\n")
    print("Feature: ", col)
    print('Skewness: ', round(df[col].skew(), 2))

    plt.figure(figsize=(18, 9))

    plt.subplot(2, 2, 1)
    df[col].hist(grid=True)
    plt.ylabel("Count")

    plt.subplot(2, 2, 2)
    sns.boxplot(data=df, x=col, hue='churn')


    #plt.subplot(2, 2, 3)
    #sns.countplot(data=df, x=col, hue='churn')


    plt.subplot(2,2,4)
    sns.boxplot(x=df[col])                           # Frequency Distribution
    plt.ylabel("Count")



    plt.show()

"""* Relation b/w "voice.plan" and "voice messages"
* At  this point , we cannot remove the outliers (availble data size )
"""

len(df[df['voice.plan']=='no'])      # Even though  Intl.plan is not active people are using Intl service unlike voice.plan

cat_cols,len(cat_cols)

"""#### churn (non-loyal) customers are about 14.2 % , considering the market level of 10 percent .It is high.

####  The output is for Imbalnced data  . We might get high accuarcy  . So dimension reduction is important fot high precision .</font>
"""

churn_counts = df['churn'].value_counts()
plt.figure(figsize=(6, 6))
plt.pie(churn_counts, labels=churn_counts.index, autopct='%1.1f%%', startangle=90, colors=['skyblue', 'salmon'])
plt.title('Churn Distribution')
plt.show()

"""* Insights  of data transformations ??? :"""

# Assuming 'no' means 0 and 'yes' means 1
df["churn"] = df["churn"].map({"no": 0, "yes": 1})

df["churn"] = df["churn"].astype("int64")

# Assuming 'no' means 0 and 'yes' means 1
df["voice.plan"] = df["voice.plan"].map({"no": 0, "yes": 1})

df["voice.plan"] = df["voice.plan"].astype("int64")

# Assuming 'no' means 0 and 'yes' means 1
df["intl.plan"] = df["intl.plan"].map({"no": 0, "yes": 1})

df["intl.plan"] = df["intl.plan"].astype("int64")

df.describe(include ='all').T

"""#### Bi-variate Analysis

#### bar plot for categorical columns vs numerical columns
"""

#bar plots ...Incoming

fig, axes = plt.subplots(2, 2, figsize = (16, 16))
fig.suptitle('Bar plot for all categorical variables in the dataset')
sns.countplot(ax = axes[0, 0], x = 'state', data = df,
              order = df['state'].value_counts().index);
sns.countplot(ax = axes[0, 1], x = 'area.code', data = df,hue = 'churn',
              order = df['area.code'].value_counts().index);
sns.countplot(ax = axes[1, 0], x = 'voice.plan', data = df,hue = 'churn',
              order = df['voice.plan'].value_counts().index);
sns.countplot(ax = axes[1, 1], x = 'intl.plan', data =df,hue = 'churn',
              order = df['intl.plan'].value_counts().index);
axes[0][0].tick_params(labelrotation = 90)

""" #### We are removing 'voice.plan' , as 'voice.messages' and 'voice.plan' are correlated.
 * Data Redundancy : When the voice.plan is inactive and voice.messages is zero.That creates redundancy as 0 'voice.messages' implies same as inactive 'voice.plan'.

 * Co-relation : The corr() between them is very high 0.95 .It might create a multi-collinearity and affect the model co-efficients.

* Simplicity : We are not losing the predictive power by removing the 'voice.plan' .We are simplifying the model and helping for more robust model.
"""

df[['intl.charge','intl.mins']].corr()

df[['night.charge','night.mins']].corr()

df[['eve.charge','eve.mins']].corr()

df[['day.charge','day.mins']].corr()

"""As charge and mins are highly correlated we can drop one of them"""

df[['voice.plan','voice.messages']].corr()

df[(df['voice.plan']==0) & (df['voice.messages']!=0)]

len(df[(df['voice.plan']==0) & (df['voice.messages']==0)])

"""#### REmoving 'voice.plan'  ---"""

df=df.drop('voice.plan',axis=1)

"""#### area.code  vs  state"""

plt.figure(figsize=(16,16))
sns.countplot( x = 'state', data = df,hue = 'area.code',
              order = df['state'].value_counts().index);
plt.show()

"""#### Attempt to see whether 'State' can be clustered into 'area.code' .It is not possible.
Since it has 51 unique values dispersed into area.code .So, we will have to careful when selecting the categorical encoding .
* NOt using  One-hot encoding label encoding
*  studying catboost encoding for this .
"""

df.nunique()

df[df['state']=='KS']                    #



pd.crosstab(df['churn'], df['intl.plan'], margins=True)

pd.crosstab(df['churn'], df['customer.calls'], margins=True)

pd.crosstab(df['customer.calls'],df['churn'],margins = True)















"""# Multi Variete Analysis"""

plt.figure(figsize=(18, 18))
sns.heatmap(df.drop(['state','area.code'],axis =1).corr(), annot = True, fmt='.2f', cmap='viridis', linewidths=2 )
plt.show()

"""# * day charge - day.mins , eve.charge -eve.mins , night.charge -night.mins , intl.charge -intl.mins , voice.plan - voice.messages    foo <font color='red'> -- Insights -->Feature Engineering....Incoming
</font> foo

# Feature Engineering
"""

df.describe(include='all').T

"""#### Standardizing the data
### Trail 1 Simple standard scaler
"""

columns_to_standardize=['account.length','voice.messages','day.calls','eve.calls','night.calls','intl.calls','day.mins','eve.mins','night.mins','intl.mins']
scaler = StandardScaler()
df[columns_to_standardize] = scaler.fit_transform(df[columns_to_standardize])

"""#### DATA REDUCTION : The "Unnamed: 0" had been removed as it is irrelevant Beacuse *** It does not have the predictive power and for predicting the churn ***"""

df =df.drop(['Unnamed: 0'],axis =1 )

# Assuming 'df' is your DataFrame
columns_to_drop = ["eve.mins", "eve.charge", "day.charge", "day.mins", "night.charge", "night.mins", "intl.charge", "intl.mins"]

# Drop the specified columns
df_filtered = df.drop(columns_to_drop, axis=1)

# Generate descriptive statistics for the remaining columns
df_filtered.describe().T

df_filtered

"""#### Using One-Hot Endcoding for area.code ,it will binary vectors for unique vectors because these are not ordinal."""

df_featured = pd.get_dummies(df_filtered, columns=['area.code'],dtype = int)

"""#### Target Encoding vs Cat boost encoding"""

# Split the data into training and test sets
train_df, test_df = train_test_split(df_featured, test_size=0.2, random_state=42)

from category_encoders.cat_boost import CatBoostEncoder

# Sample training and testing datasets with a categorical column
train_data = train_df
test_data = test_df.drop(['churn'],axis =1)

# Initialize the CatBoostEncoder
catboost_encoder = CatBoostEncoder()

# Fit and transform the training data
train_encoded_state_cat = catboost_encoder.fit_transform(train_data['state'], train_data['churn'])

# Transform the testing data
test_encoded_state_cat = catboost_encoder.transform(test_data['state'])

# Initialize the MeanEncoder
mean_encoder = ce.TargetEncoder()

# Fit the encoder on the training data
mean_encoder.fit(train_df['state'], train_df['churn'])

# Transform both the training and test datasets
train_encoded_target = mean_encoder.transform(train_df['state'])
test_encoded_target = mean_encoder.transform(test_df['state'])

# Display the encoded datasets
print("Training Data (After Mean Encoding):\n", train_encoded_target)
print("\nTest Data (After Mean Encoding):\n", test_encoded_target)

train_df['state_target']= train_encoded_target
test_df['state_target'] = test_encoded_target

train_encoded_state_cat

"""* removing the state feature after encoding with target encoding"""

train_df=train_df.drop('state',axis=1)

test_df=test_df.drop('state',axis=1)

train_df.info()

test_df.info()





"""#### EDA done

* Lets start with Logistic regression
"""



x_train = train_df.drop('churn',axis =1)
y_train = train_df['churn']

x_test =test_df.drop('churn',axis =1)
y_test = test_df['churn']

x_train.describe(include ='all').T

"""look for null values or NaN values"""

x_test.isna().sum()

x_train.isna().sum()



"""#### Start Handling the Imbalanced data with Over sampling ."""

from imblearn.over_sampling import SMOTE


#x_train, x_test, y_train, y_test = train_test_split(x_train, y_train, test_size=0.3, random_state=0)

print("Number transactions X_train dataset: ", x_train.shape)
print("Number transactions y_train dataset: ", y_train.shape)
print("Number transactions X_test dataset: ", x_test.shape)
print("Number transactions y_test dataset: ", y_test.shape)

print("Before OverSampling, counts of label '1': {}".format(sum(y_train==1)))
print("Before OverSampling, counts of label '0': {} \n".format(sum(y_train==0)))

sm = SMOTE(random_state=2)
x_train_res, y_train_res = sm.fit_resample(x_train, y_train.ravel())

print('After OverSampling, the shape of train_X: {}'.format(x_train_res.shape))
print('After OverSampling, the shape of train_y: {} \n'.format(y_train_res.shape))

print("After OverSampling, counts of label '1': {}".format(sum(y_train_res==1)))
print("After OverSampling, counts of label '0': {}".format(sum(y_train_res==0)))



accuracy = {}

lr= LogisticRegression()
lr.fit(x_train, y_train)
ACC = lr.score(x_test,y_test)*100

accuracy['Logistic Regression without Feature Selection'] = ACC
print("Test Accuracy {:.3f}%".format(ACC))

y_pred = lr.predict(x_test)

# Assuming y_test and y_pred are your true labels and predicted labels, respectively
conf_matrix = confusion_matrix(y_test, y_pred)

# Print the confusion matrix
print("Confusion Matrix:")
print(conf_matrix)
sns.heatmap(conf_matrix,annot =True,cmap ='viridis' ,fmt = "d")

"""### Confusion matrix
Table that describes the performance of a classification model

A confusion matrix is a tool for summarizing the performance of a classification algorithm. A confusion matrix will give us a clear picture of classification model performance and the types of errors produced by the model. It gives us a summary of correct and incorrect predictions broken down by each category. The summary is represented in a tabular form.

Four types of outcomes are possible while evaluating a classification model performance. These four outcomes are described below:-

True Positives (TP) – True Positives occur when we predict an observation belongs to a certain class and the observation actually belongs to that class.

True Negatives (TN) – True Negatives occur when we predict an observation does not belong to a certain class and the observation actually does not belong to that class.

False Positives (FP) – False Positives occur when we predict an observation belongs to a certain class but the observation actually does not belong to that class. This type of error is called Type I error.

False Negatives (FN) – False Negatives occur when we predict an observation does not belong to a certain class but the observation actually belongs to that class. This is a very serious error and it is called Type II error.

These four outcomes are summarized in a confusion matrix given below.
"""

report = classification_report(y_test, y_pred)

# Print the report
print(report)

"""Binning"""





from imblearn.over_sampling import SMOTE


x_train, x_test, y_train, y_test = train_test_split(x_train, y_train, test_size=0.3, random_state=0)

print("Number transactions X_train dataset: ", x_train.shape)
print("Number transactions y_train dataset: ", y_train.shape)
print("Number transactions X_test dataset: ", x_test.shape)
print("Number transactions y_test dataset: ", y_test.shape)

print("Before OverSampling, counts of label '1': {}".format(sum(y_train==1)))
print("Before OverSampling, counts of label '0': {} \n".format(sum(y_train==0)))

sm = SMOTE(random_state=2)
x_train_res, y_train_res = sm.fit_resample(x_train, y_train.ravel())

print('After OverSampling, the shape of train_X: {}'.format(x_train_res.shape))
print('After OverSampling, the shape of train_y: {} \n'.format(y_train_res.shape))

print("After OverSampling, counts of label '1': {}".format(sum(y_train_res==1)))
print("After OverSampling, counts of label '0': {}".format(sum(y_train_res==0)))

from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, precision_recall_curve, auc, roc_auc_score, roc_curve, recall_score, classification_report

parameters = {
    'C': np.linspace(1, 10, 10)
             }
lr = LogisticRegression()
clf = GridSearchCV(lr, parameters, cv=5, verbose=5, n_jobs=3)
clf.fit(x_train_res, y_train_res.ravel())

clf.best_params_

lr1 = LogisticRegression(C=10,penalty='l2', verbose=5)
lr1.fit(x_train_res, y_train_res.ravel())

import itertools

def plot_confusion_matrix(cm, classes,
                          normalize=False,
                          title='Confusion matrix',
                          cmap=plt.cm.Blues):
    """
    This function prints and plots the confusion matrix.
    Normalization can be applied by setting `normalize=True`.
    """
    plt.imshow(cm, interpolation='nearest', cmap=cmap)
    plt.title(title)
    plt.colorbar()
    tick_marks = np.arange(len(classes))
    plt.xticks(tick_marks, classes, rotation=0)
    plt.yticks(tick_marks, classes)

    if normalize:
        cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
        #print("Normalized confusion matrix")
    else:
        1#print('Confusion matrix, without normalization')

    #print(cm)

    thresh = cm.max() / 2.
    for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
        plt.text(j, i, cm[i, j],
                 horizontalalignment="center",
                 color="white" if cm[i, j] > thresh else "black")

    plt.tight_layout()
    plt.ylabel('True label')
    plt.xlabel('Predicted label')
y_train_pre = lr1.predict(x_train)

cnf_matrix_tra = confusion_matrix(y_train, y_train_pre)

print("Recall metric in the train dataset: {}%".format(100*cnf_matrix_tra[1,1]/(cnf_matrix_tra[1,0]+cnf_matrix_tra[1,1])))


class_names = [0,1]
plt.figure()
plot_confusion_matrix(cnf_matrix_tra , classes=class_names, title='Confusion matrix')
plt.show()

report1 = classification_report(y_train, y_train_pre)
print(report1)

tmp = lr1.fit(x_train_res, y_train_res.ravel())

y_pred_sample_score = tmp.decision_function(x_test)


fpr, tpr, thresholds = roc_curve(y_test, y_pred_sample_score)

roc_auc = auc(fpr,tpr)

# Plot ROC
plt.title('Receiver Operating Characteristic')
plt.plot(fpr, tpr, 'b',label='AUC = %0.3f'% roc_auc)
plt.legend(loc='lower right')
plt.plot([0,1],[0,1],'r--')
plt.xlim([-0.1,1.0])
plt.ylim([-0.1,1.01])
plt.ylabel('True Positive Rate')
plt.xlabel('False Positive Rate')
plt.show()

roc_auc

